---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 2926128973-VdOyAS1I3tUQcokDXclauujHaqcrd8i7Qb35UO5
:access_token_secret: 3AJ7SEnvmTF8FLGWznlm0P2uEgvhml2vW6qWTl0VdfwpV
